### ISSUE TITLE
Reversed names (Last, first)

### ISSUE THREAD

**Issue by lmullen** [Ironholds/humaniformat#1]
This is a really useful package. Thanks a lot.

Do you intend to support inverted names? E.g.

```
parse_names("Keyes, Oliver")
```

**Comment by Ironholds** [comment]
Indirectly! So the plan is to provide a format_names function that (relatively) standardises names. So you'll be able to pass it 'Keyes, Oliver' or 'Keyes Esq., Oliver', or similar, and it will reformat them. So the eventual workflow will look something like:

```
parsed_names <- format_names(names) %>% parse_names
```

The only intended /direct/ change to parse_names is to support multiple suffixes: I'd like to be able to support as many formats as possible while avoid obfuscating the code and making future maintenance hard.

Does this make sense/sound good?

**Comment by lmullen** [comment]
Absolutely. It makes sense to have the separate `format_names()` function.

On Fri, Aug 21, 2015 at 8:31 PM, Oliver Keyes notifications@github.com
wrote:

> Indirectly! So the plan is to provide a format_names function that
> (relatively) standardises names. So you'll be able to pass it 'Keyes,
> Oliver' or 'Keyes Esq., Oliver', or similar, and it will reformat them. So
> the eventual workflow will look something like:
> 
> parsed_names <- format_names(names) %>% parse_names
> 
> The only intended /direct/ change to parse_names is to support multiple
> suffixes: I'd like to be able to support as many formats as possible while
> avoid obfuscating the code and making future maintenance hard.
> 
> Does this make sense/sound good?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Ironholds/humaniformat/issues/1#issuecomment-133600347
> .

## 

Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University

**Comment by Ironholds** [comment]
Awesome! That's my next chunk to do (most of the code is sitting there, I just need to shake it until it works)

**Comment by Ironholds** [comment]
@lmullen format_reverse should now do what you want :)

**Comment by lmullen** [comment]
Awesome!
