### ISSUE TITLE
Last Name, Firstname

### ISSUE THREAD

**Issue by tslumley** [Ironholds/humaniformat#2]
People with spaces in their last names will always be a problem, but I would have thought

Nielsen Hayden, Patrick

makes more sense with "Nielsen Hayden" as the lastname and "Patrick" as the firstname, rather than the other way around.

**Comment by Ironholds** [comment]
So, parse_names doesn't currently respect commas (in the sense of caring about them). There's format_reverse, which should be linked from parse_names (if not I'll fix that) and is designed to reverse and reformat "Nielsen Hayden, Patrick" into "Patrick Nielsen Hayden" for parsing.

(Admittedly that produces "Nielsen" as a middle name, which isn't great).

The problem of comma-based parsing is that 'Nielsen Hayden, Patrick' needs to be reversed - but 'Thomas Lumley, PhD' doesn't. There's probably a way of resolving this using the check for suffixes, but the logic escapes me pre-coffee. I'll noodle on it later and see if I can come up with anything.

**Comment by Ironholds** [comment]
Yeah, I can't think of a good way of doing it that doesn't introduce additional edge cases :/. Your best bet is format_reverse %>% parse_names.
