### ISSUE TITLE
Integrate diminutives?

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/humaniformat#4]
Using https://github.com/dtrebbien/diminutives.db and triebeard we could do speedy diminutive-to-longest-name expansion although need to be sensitive around binary gender in language

**Comment by Ironholds** [comment]
@leeper as one of the people I recall liking this package, would this be a useful feature to you?

**Comment by leeper** [comment]
That could be interesting. How easy would it be to incorporate?

**Comment by Ironholds** [comment]
Pretty trivial. I'd just store the diminutives in a (formatted) .rda, throw them into a trie on load with the diminutives as keys and the full names as values, and run longest_match(trie, names_to_expand). The complicated bit comes around gender: I guess I could either (a) have a parameter of "should this default to male or female names on ambiguity" or (b) allow the passing in of a vector of binary gender values, and then switch each element of the vector accordingly, which would let things like genderiser come into play.

**Comment by Ironholds** [comment]
Closing because the false gender binary is a pile of steaming horseshit
